#-------------------------------
# General Site Settings

title: Powell Games


menu:
- {name: Paint Big, url: 'https://robertdpowell.github.io/powellgames/paintbig.html'}
- {name: Paint Small, url: 'https://robertdpowell.github.io/powellgames/paintsmall.html'}
- {name: Circles, url: 'https://robertdpowell.github.io/powellgames/hovercircles.html'}
- {name: Spelling, url: 'https://robertdpowell.github.io/powellgames/spelling.html'}
- {name: Numbers, url: 'https://robertdpowell.github.io/powellgames/numbers.html'}
