#-------------------------------
# General Site Settings

title: Emilia's Games


blurb: >
  Rob specializes in making other people [look good]
  Most of the things he makes are [digital interfaces](http://atradius.com {:target="_blank"},
  but he also puts effort into crafting [next-level beats](http://soundcloud.com/travis-neilson){:target="_blank"}
  and [YouTube videos](http://youtube.com/user/devtipsfordesigners){:target="_blank"} about making change happen.


menu:
- {name: Painting, url: 'http://localhost:3000/paint.html'}
- {name: Hover Circles, url: 'http://localhost:3000/hovercircles.html'}




#-------------------------------
# Clients Section



#-------------------------------
# Contact Section


# can be 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'soundcloud'
  